server:
  port: 8084

spring:
  application:
    name: WALLET-TRANSACTION-SERVICE   # ⭐ keep uppercase (match Eureka)

  datasource:
    url: jdbc:postgresql://localhost:5432/transaction_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
